; Listing generated by Microsoft (R) Optimizing Compiler Version 19.00.23026.0 

include listing.inc

INCLUDELIB LIBCMT
INCLUDELIB OLDNAMES

PUBLIC	QEnqueue
PUBLIC	QAddItem
EXTRN	LclAlloc:PROC
pdata	SEGMENT
$pdata$QAddItem DD imagerel $LN8
	DD	imagerel $LN8+93
	DD	imagerel $unwind$QAddItem
pdata	ENDS
xdata	SEGMENT
$unwind$QAddItem DD 040a01H
	DD	06340aH
	DD	07006320aH
xdata	ENDS
; Function compile flags: /Ogtpy
; File d:\hjwasm\hjwasm2.13.1s\hjwasm2.13.1s\queue.c
_TEXT	SEGMENT
q$ = 48
data$ = 56
QAddItem PROC

; 63   : {

$LN8:
	mov	QWORD PTR [rsp+8], rbx
	push	rdi
	sub	rsp, 32					; 00000020H
	mov	rdi, rcx
	mov	rbx, rdx

; 64   :     struct qnode    *node;
; 65   : 
; 66   :     node = LclAlloc( sizeof( struct qnode ) );

	mov	ecx, 16
	call	LclAlloc
	mov	rdx, rax

; 67   :     node->elmt = data;

	mov	QWORD PTR [rax+8], rbx

; 68   :     QEnqueue( q, node );

	cmp	QWORD PTR [rdi], 0
	jne	SHORT $LN4@QAddItem
	mov	QWORD PTR [rdi+8], rax
	mov	QWORD PTR [rdi], rax
	mov	QWORD PTR [rax], 0

; 69   : }

	mov	rbx, QWORD PTR [rsp+48]
	add	rsp, 32					; 00000020H
	pop	rdi
	ret	0

; 68   :     QEnqueue( q, node );

$LN4@QAddItem:
	mov	rax, QWORD PTR [rdi+8]

; 69   : }

	mov	rbx, QWORD PTR [rsp+48]
	mov	QWORD PTR [rax], rdx
	mov	QWORD PTR [rdi+8], rdx
	mov	QWORD PTR [rdx], 0
	add	rsp, 32					; 00000020H
	pop	rdi
	ret	0
QAddItem ENDP
_TEXT	ENDS
; Function compile flags: /Ogtpy
; File d:\hjwasm\hjwasm2.13.1s\hjwasm2.13.1s\queue.c
_TEXT	SEGMENT
q$ = 8
item$ = 16
QEnqueue PROC

; 49   :     if( q->head == NULL ) {

	cmp	QWORD PTR [rcx], 0
	jne	SHORT $LN2@QEnqueue

; 50   :         q->head = q->tail = item;

	mov	QWORD PTR [rcx], rdx

; 54   :         q->tail = item;

	mov	QWORD PTR [rcx+8], rdx

; 55   :     }
; 56   :     *(void**)item = NULL;

	mov	QWORD PTR [rdx], 0

; 57   : }

	ret	0
$LN2@QEnqueue:

; 51   :     } else {
; 52   : /**/    myassert( q->tail != NULL );
; 53   :         *(void **)q->tail = item;

	mov	rax, QWORD PTR [rcx+8]
	mov	QWORD PTR [rax], rdx

; 54   :         q->tail = item;

	mov	QWORD PTR [rcx+8], rdx

; 55   :     }
; 56   :     *(void**)item = NULL;

	mov	QWORD PTR [rdx], 0

; 57   : }

	ret	0
QEnqueue ENDP
_TEXT	ENDS
END
