ARITH3.ASO(14) : Error A2048: Operands must be the same size: 1 - 2
ARITH3.ASO(15) : Error A2048: Operands must be the same size: 1 - 2
ARITH3.ASO(16) : Error A2048: Operands must be the same size: 1 - 2
ARITH3.ASO(18) : Error A2048: Operands must be the same size: 2 - 4
ARITH3.ASO(19) : Error A2048: Operands must be the same size: 2 - 4
ARITH3.ASO(20) : Error A2048: Operands must be the same size: 2 - 4
ARITH3.ASO(22) : Error A2235: Constant value too large: 100000000h
ARITH3.ASO(23) : Error A2235: Constant value too large: 100000000h
ARITH3.ASO(24) : Error A2235: Constant value too large: 100000000h
