ASSUME8.ASO(9) : Error A2069: Segment, group or segment register expected
ASSUME8.ASO(10) : Error A2069: Segment, group or segment register expected
ASSUME8.ASO(11) : Error A2069: Segment, group or segment register expected
ASSUME8.ASO(12) : Error A2069: Segment, group or segment register expected
ASSUME8.ASO(13) : Error A2069: Segment, group or segment register expected
ASSUME8.ASO(14) : Error A2069: Segment, group or segment register expected
ASSUME8.ASO(15) : Error A2069: Segment, group or segment register expected
ASSUME8.ASO(16) : Error A2030: Instruction or register not accepted in current CPU mode
