INVOKE39.ASO(25) : Error A2145: INVOKE argument type mismatch: argument 1
INVOKE39.ASO(26) : Error A2145: INVOKE argument type mismatch: argument 1
INVOKE39.ASO(27) : Error A2145: INVOKE argument type mismatch: argument 1
INVOKE39.ASO(28) : Error A2145: INVOKE argument type mismatch: argument 1
INVOKE39.ASO(29) : Error A2145: INVOKE argument type mismatch: argument 1
INVOKE39.ASO(30) : Error A2145: INVOKE argument type mismatch: argument 1
INVOKE39.ASO(31) : Error A2145: INVOKE argument type mismatch: argument 1
INVOKE39.ASO(32) : Error A2145: INVOKE argument type mismatch: argument 1
