MEMMULT.ASO(18) : Error A2182: Instruction operand must have size
MEMMULT.ASO(19) : Error A2182: Instruction operand must have size
MEMMULT.ASO(20) : Error A2182: Instruction operand must have size
MEMMULT.ASO(21) : Error A2182: Instruction operand must have size
MEMMULT.ASO(22) : Error A2182: Instruction operand must have size
MEMMULT.ASO(23) : Error A2182: Instruction operand must have size
MEMMULT.ASO(25) : Warning A4073: Size not specified, assuming: BYTE
