OVERRID3.ASC(10) : Error A2170: Invalid use of register
OVERRID3.ASC(11) : Error A2170: Invalid use of register
OVERRID3.ASC(12) : Error A2170: Invalid use of register
OVERRID3.ASC(13) : Error A2170: Invalid use of register
OVERRID3.ASC(16) : Error A2170: Invalid use of register
OVERRID3.ASC(18) : Error A2170: Invalid use of register
OVERRID3.ASC(21) : Error A2170: Invalid use of register
OVERRID3.ASC(23) : Error A2170: Invalid use of register
