PUSH3.ASO(35) : Error A2049: Invalid instruction operands
PUSH3.ASO(38) : Error A2049: Invalid instruction operands
PUSH3.ASO(39) : Error A2049: Invalid instruction operands
PUSH3.ASO(43) : Error A2049: Invalid instruction operands
PUSH3.ASO(45) : Error A2049: Invalid instruction operands
PUSH3.ASO(48) : Error A2049: Invalid instruction operands
PUSH3.ASO(49) : Error A2049: Invalid instruction operands
PUSH3.ASO(53) : Error A2049: Invalid instruction operands
