SEGMENT2.ASO(6) : Error A2132: Incompatible CPU mode for 32-bit segment
SEGMENT2.ASO(9) : Error A2132: Incompatible CPU mode for 32-bit segment
SEGMENT2.ASO(12) : Error A2132: Incompatible CPU mode for 64-bit segment
SEGMENT2.ASO(15) : Error A2132: Incompatible CPU mode for 32-bit segment
SEGMENT2.ASO(18) : Error A2132: Incompatible CPU mode for 64-bit segment
SEGMENT2.ASO(23) : Error A2132: Incompatible CPU mode for 64-bit segment
SEGMENT2.ASO(26) : Error A2132: Incompatible CPU mode for 64-bit segment
