TYPES4.ASO(14) : Error A2136: Symbol type conflict: TD2
TYPES4.ASO(30) : Error A2136: Symbol type conflict: TD3
TYPES4.ASO(34) : Error A2136: Symbol type conflict: TD4
TYPES4.ASO(37) : Error A2136: Symbol type conflict: TD5
TYPES4.ASO(43) : Error A2136: Symbol type conflict: TD7
TYPES4.ASO(49) : Error A2136: Symbol type conflict: TD9
TYPES4.ASO(52) : Error A2136: Symbol type conflict: TD10
TYPES4.ASO(55) : Error A2137: Conflicting parameter definition: 
TYPES4.ASO(58) : Error A2136: Symbol type conflict: TD12
